services:
  - type: web
    name: quiz-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: ADMIN_CODE
        value: "0709"
      - key: DATA_DIR
        value: /data
      - key: MONGODB_URI
        value: "mongodb+srv://Christus:voldigo225@cluster0.hphrncx.mongodb.net/?appName=Cluster"
      - key: MONGODB_DB
        value: quizdb
    disk:
      name: quiz-data
      mountPath: /data
      sizeGB: 1
